### ISSUE TITLE
Encoding named entities with "of"

### ISSUE THREAD

**Issue by scottkleinman** [scottkleinman/aeme#49]
How do we handle names like "Herebard of Boseham"? Is it

```xml
<name type="person" ref="#bioHerebardOfBoseham">Herebard</name> of 
<name type="place" ref="#locBoseham">Boseham</name>
```
or
```xml
<name type="person" ref="#bioHerebardOfBoseham">Herebard of Boseham</name>
```
or
```xml
<name type="person" ref="#bioHerebardOfBoseham">Herebard of 
    <name type="place" ref="#locBoseham">Boseham</name>
</name>
```

**Comment by mmwwah** [comment]
I hesitate to weigh in, but my preference is for Door Number One, because it treats the name and the location as being of equal scholarly value.  At least as I understand it.  Door Number Two says that the place isn’t of interest, and Door Number Three says that the name isn’t (all apart from the person).

Or am I misreading?

meg

(Don’t know why I’m weighing in, except to say that I’m paying attention.  Carry on.)

**Comment by scottkleinman** [comment]
Meg's logic seems sound to me. I suppose it was too late last night for me to type door number four:

```xml
<name type="person" ref="#bioHerebardOfBoseham">
    <name type="person" ref="#bioHerebardOfBoseham">Herebard</name> of 
    <name type="place" ref="#locBoseham">Boseham</name>
</name>
```
There are variations on the above, such as making the outer `<name>` element `<name type="association">` or even just wrapping the phrase in `<seg>`. If we do want to make some kind of association, the latter might be preferable just because it's less verbose. I'll check today whether I can find any discussion in the TEI Guidelines, but I suspect it will all be devoted to structured biographical records.

**Comment by skgoetz** [comment]
I agree with Meg.

**Comment by skgoetz** [comment]
If you haven't already, I'd suggest checking the archives/wikis for TEI-L,
TEI-MS-SIG, and TEI-Correspondence-SIG, which may have more specific
suggestions than the Guidelines. (I don't always agree with what I find,
but the specificity helps with ideas.) I'd do it but am still quite stuck.

**Comment by scottkleinman** [comment]
To some extent, this issue is mirrored in other phrasal entities such as "Saint Vincent". But I agree that Meg's suggestion is the best method for dealing with names linked by "of" or "de" at this stage. If we want to associate the two named elements at a later stage, it should be easy to do so algorithmically. I'll close this for now.
