### ISSUE TITLE
<add @place="vertical">?

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#51]
In Junius 1, there are many (read: manymanymany) additions that read vertically.  I think we need something like [@place="verticalRight"] and [@place="verticalLeft"] -- and possibly [@place="verticalCenter"] although I need to doublecheck on that.

Can we define something like that?  Thoughts?

**Comment by scottkleinman** [comment]
I initially misunderstood this issue as relating to an insufficient number of categories for representing placement in the margins (e.g. topLeft, topCenter, topRight). I do think we need to consider whether this needs to be broken up further, especially for the left and right margins.

But I think the issue with the Ormulum is the text orientation. Check out the [TEI guidelines on this](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/WD.html#WDWM) to see if there is anything useful there (at first glance, it seems oriented towards whole writing systems with different orientations, such as Chinese, but I haven't read closely).

**Comment by mmwwah** [comment]
Okay, I think we can resolve this one.  Yes, there are robust guidelines for this at 5.7.3.  Thanks, Scott!
