### ISSUE TITLE
repo file structure

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#62]
I'm a bit confused by the organization of the AEME repo.  There seems to be a fair amount of duplication (or maybe I'm missing specifics).  Which files do I need to be paying attention to and/or ignoring when I'm looking for Laud 108 analogues?

**Comment by scottkleinman** [comment]
The `bodllaudmisc108` folder has:

* `entities.dtd`
* `teiHeader.xml`
* `facsimile.xml`

Then it has one xml file for each of the saints' lives and other texts in the manuscript. Once each text has been completely edited, they will be combined into single xml file for the entire manuscript, with one `<teiHeader>` and one `<facsimile>` element in the same file.

Any other files you see in the `bodllaudmisc108` folder are ephemeral. Most of the manuscript has now undergone some preliminary editing. It's safe to use almost any of the saints' lives as a model--to the extent that any features of Laud Misc. 108 are duplicated in Junius 1.

**Comment by mmwwah** [comment]
Great -- thanks.
