### ISSUE TITLE
and now, the dumbest question of all!

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#63]
HOW do I get an .xml file into GitHub Desktop so that I can push it back to GitHub?  I am so not getting how GitHub Desktop works.  Can one do without it?

**Comment by scottkleinman** [comment]
If you have already cloned the aeme repo on your local computer, open the GitHub client and right click on the aeme repo in the list of repositories. Select `Open in Explorer` (which will be something different if you have a Mac). You can also select `Open in Git Shell` to see the path to your local GitHub repo. Save your files into that folder.

Go back to the GitHub client and click `Changes` at the top. You'll get a list of all the changed files in your repo. Click the check boxes for all files you wish to push to GitHub. Type a short summary of the changes you are committing at the bottom of the screen and then click `Commit to master`. You've now committed the changes. The next step is to push them to GitHub. To do this, click the `Sync` button in top right corner of the screen.

It's not entirely the most intuitive interface, but hopefully this helps.

**Comment by skgoetz** [comment]
git add filename 
git commit -m "remarks here" 
git push
--
Sent via phone.

**Comment by skgoetz** [comment]
trying again  from correct email address 

git add filename 
git commit -m "remarks here" 
git push
--
Sent via phone.

**Comment by mmwwah** [comment]
Great -- thanks.

O command line, don't ever leave me.

**Comment by mmwwah** [comment]
Closed too soon.  Because I was editing /dedication/entities.dtd directly in GitHub, rather than in my branch (/meg-dedication) and via oXygen, the /dedication/entities.dtd is more up to date than the one in /meg-dedication (which is the branch that I want to use as the most up-to-date, the vetted one.  

How do I copy a single file over to my branch?  I tried Compare Files, but it was only offering the main code file, not *.dtd.

**Comment by mmwwah** [comment]
Also, what's the best way to change the name of a file, and to combine two files?  Zach separated each section of the text (Dedication, etc), but according to the Guidelines, we will want one `ormulum.xml` file, right?  How to go about fixing that?

**Comment by scottkleinman** [comment]
You can continue to work in separate files and combine them at the end, but that just depends on what is most convenient for you.

But this is really a git/GitHub question. To change a file name, just change it on the desktop in your local folder. Then commit and push. To combine files, just paste one at the end of the other, save the file, and then delete the first file. Then commit and push. The result in the git repository will be an update and a deletion.

It sounds to me like you edited `entities.dtd` in the master branch, but I'm not sure from your description whether your local copy is the most up-to-date. If it is, just change to your branch in GitHub, commit, and push. In the GitHub client, you can just click on **master**, and you'll see other branches pop up. Select one the change branches.

**Comment by mmwwah** [comment]
File manipulation: Thanks.  Got it.

I made one round of edits in the master branch, but all subsequent edits have been done in meg-ded.  I reckon I'll push to master later.
