### ISSUE TITLE
working my way through the tei header

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#64]
This line:
```The manuscript contents are catalogued in DIMEV entry <ref
                        target="http://www.dimev.net/Records.php?MSS=BodJunius1" type="DIMEV"
                            >http://www.dimev.net/Records.php?MSS=BodJunius1</ref>. All items belong
                        to the <ref type="LAEME">LAEME</ref>
                        <term>literary</term> category.```

What does "All items belong to LAEME literary category" mean?  What items -- each saint's life and poem?  Esp. since that's the first reference to LAEME in the header.  J'confuse. 

I've been tweaking the Junius 1 tei header in my branch.  I'll submit it for your approval when I'm done.

**Comment by mmwwah** [comment]
Also, Laud 108 has a line in the `<msContents>`element saying that a full description can be found at WMW.  I've changed that to *Production and Use of English MSS 1060-1220*, and I've abbreviated it "PUEM," following the analogy of "WMW."  Do I need to declare/define that acronym anywhere?

**Comment by scottkleinman** [comment]
The full sentence reads: "All items belong to the <ref type="LAEME">LAEME</ref> <term>literary</term> category." For this, see the following code in the `<teiHeader>`:

```xml
    <profileDesc>
        <textClass>
            <keywords scheme="#LAEME">
                <term>literary</term>
            </keywords>
            <keywords>
                <term>hagiography</term>
                <term>romance</term>
            </keywords>
        </textClass>
    </profileDesc>
```
Essentially, these are keywords defined for the type of text contained within the manuscript. See further [`encodingDesc`](http://scottkleinman.net/wp-content/uploads/guidelines-4.0/The_teiHeader_Section/encodingDesc). The introduction to the LAEME catalogue provides a rough taxonomy of text types, so all this is saying is that all texts in Laud Misc. 108 are of the "literary" type as defined by LAEME. You probably won't need to change that for Junius 1 (except maybe "all texts" since it's just one text). It is possible to define other taxonomy keywords in the `<teiHeader>` as shown above, if you wish.

For defining the Production and Use of English, see the following as a model:

```xml
    <encodingDesc>
        <classDecl>
            <taxonomy xml:id="LAEME">
                <bibl>
                    <title>Catalogue of Sources for a Linguistic Atlas of Early Medieval
                        English</title>
                    <author>Margaret Laing</author>
                    <edition>1993</edition>
                </bibl>
            </taxonomy>
            <taxonomy xml:id="MWM">
                <bibl>
                    <title>Manuscripts of the West Midlands: A Catalogue of Vernacular Manuscript
                        Books of the English West Midlands, c. 1300 - c. 1475</title>
                    <author>Wendy Scase</author>
                    <edition>2009</edition>
                </bibl>
            </taxonomy>
        </classDecl>
    </encodingDesc>
```
Your abbreviation should be the `@xml:id` in `<taxonomy>`.

**Comment by mmwwah** [comment]
Yeah, I realized that I hadn't read it correctly.  I was hoping that my edit of the question would cover up my lapse ;-)

I couldn't find any taxonomy of types of documents in LAEME.  DIMEV classifies Junius 1 as "utilitarian verse" (!!!) and "verse sermons."  That seems closer to the mark than "literary" to me.

**Comment by scottkleinman** [comment]
"Utilitarian verse" ha! ha! ha!

LAEME doesn't really express its taxonomy as a taxonomy. Section 2 of the introduction provides the following types of texts (with some sub-sections depending on whether they are copies of Old English texts):

* Documents
* Literary texts
* Glosses

That's it. This has the advantage of providing a queryable structure that is not very prescriptive. Getting more specific should be the job of the editor. As to the literary category, LAEME includes "(a) major works in prose such as homilies, rules...biblical translations and paraphrases, chronicles and grammars; (b) lengthy works in verse..." (p. 5). According to this wide definition the *Ormulum* is "literary" in content and form. But this is the bare minimum required by AEME. You can define a taxonomic category for homily, for instance.

**Comment by mmwwah** [comment]
Okay, cool.  Thanks.  I still can't find that in the LAEME overview, but I'm running with it anyway.

**Comment by mmwwah** [comment]
When defining "PUEM" as above, do multiple authors go in one tag or must each be tagged separately?

**Comment by scottkleinman** [comment]
I'm not sure. You might be able to find some suggestions [here](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COBITY).

**Comment by mmwwah** [comment]
I have now worked my way through every line of the header.  I don't think I broke anything; it seems to validate.  If y'all want to check my work, feel free -- but don't feel obligated.

**Comment by scottkleinman** [comment]
I'm happy to have a look after you've pushed to GitHub. It will be useful to see a version that's not for Laud Misc. 108.

**Comment by mmwwah** [comment]
It's up, under the meg-dedication branch.

**Comment by mmwwah** [comment]
Also, see file-manipulation questions under the "easy one" issue (which I reopened).

**Comment by scottkleinman** [comment]
I see that you haven't done everything, but the changes you have made for Junius 1 look good for me. that said, I'm a little worried about the "meg-dedication" branch. Sounds a bit like Orm dedicated the Ormulum to you...

**Comment by mmwwah** [comment]
Bwahahaha!  Just think of it as meg-edited.  I wanted to retain Zach's branch intact in case I screwed everything up.  My intention is to NOT screw everything up and eventually push my branch back to `master`.

I have indeed left some things for later, most notably the `<history>` section.  I couldn't remember the year that Van Vliet acquired the ms, when he died and Junius got it, etc.
