### ISSUE TITLE
automated expansions

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#67]
I don't know the first thing about style sheets, so I'm just checking:  Some very consistent features can be automatically expanded in the CritV and not in the DipV, right, so we don't have to encode `<choice>` by hand every single time?

The two things I'm thinking of at the moment are `&#xA765;` (thorn-bar) for "that" and the single word "i" (sans macron) for "in."  But I'm sure there will be others.

So, if I'm wrong and this can't be automated, let me know and I'll go back and choicify everything.

**Comment by scottkleinman** [comment]
AEME uses some "[TEI-conformant](http://www.tei-c.org/Support/Learn/intro.xml#body.1_div.3_div.1)" custom elements like `<sg/>`. A word like `a<sg/>boue` can easily be expanded to standard TEI:

```xml
<choice>
   <orig>a boue</orig>
    <reg>aboue</reg>
</choice>
```
For "that", you should probably use 

```xml
<choice>
   <abbr>&#xA765;</abbr>
    <expan>þat</expan>
</choice>
```
However, you could define `&#xA765;` (or something like `&#thornbarthat;`) as the following:

```xml
<choice><abbr>&#xA765;</abbr><expan>þat</expan></choice>
`
That way your code would be a little easier on the eye.

It occurred to me that this would be particularly useful for the various common abbreviations of Jesus.

**Comment by mmwwah** [comment]
Ah.  I had read about the shadow gap issue in the Guidelines, but it didn't occur to me that a missing letter (the /n/ in "in") would count as a shadow gap.  Or am I misunderstanding you?  (The more I think about it, the more I think I'm missing your point....)

The big picture is that nothing can be automatically converted for the CritV by stylesheets -- that all the action is via `<choice>`, even if you automate it with an elegant solution like your `&#thornbarthat;`.  Have I got that right?

**Comment by mmwwah** [comment]
Okay, I've just gone back over some of the code for Mary of Egypt, and I don't see any encoding for the CritV (or I don't recognize it as such).  The first `<choice>` is at line 70 (capitalizing or not capitalizing "leinte"), and a similar intervention has not been made for "e/Egypt."  

Does that mean y'all are doing a later pass to encode the CritV material?  There's a way in which that would suit me fine, since if I had a robust DipV ready, I'd feel more confident about my tenure dossier, as opposed to a mostly-fine version of both.

**Comment by scottkleinman** [comment]
For the form "i" used for "in", see issue #68.

The style sheets can be responsive to custom elements like `<sg/>` but these have to be TEI-conformant, so effectively what you say is correct.

The Mary of Egypt file is a stage 1 editing file. Stage 2 includes proof-reading and dealing more closely with capitalisation. So, yes, a later pass will take place.
