### ISSUE TITLE
audience

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#68]
This is rather more philosophical that most of my other Issues.

Who are we envisioning as the reader of the Critical View?  

This doesn't seem as easy a question for Junius 1 as for Laud 108, because the spelling and paleography/process of the Ormulum are perhaps its most valuable aspects (for teaching or whatever).  If we regularized and modernized those, the CritV would be of only minor use to anyone.

I'm developing answers of my own to this question, but I'm very interested in hearing how y'all think the CritV would, could, and should be used.

On a related note, when you were making initial decisions about Laud 108, did you have a kitchen cabinet of folks to consult about what they would like to see in it?  I'm thinking about asking Adrienne, Carla, and possibly Mark Faulkner -- the last three people besides myself to look at the ms. -- if they would be an informal advisory board.  Thoughts?

**Comment by scottkleinman** [comment]
We probably should have had an "informal advisory board" for Laud Misc. 108, but instead I went will extrapolating from the general discussions we had plus our AEME Advisory Board meeting.

But the point you make is an interesting one. Different manuscripts will have different requirements. I think an important audience for the critical view will be students for whom the text needs to be accessible (especially to students at non-selective institutions who will generally find it more challenging). In many teaching situations, the interest will not be palaeographical and codicological issues, and it may be valuable to let provide a more traditionally-formatted text. The same is true in scholarly scenarios, where we often choose to cite texts edited with modern punctuation, capitalisation, and so on.

But there is also a difference between the critical view and the critical *markup*, which contains editorial apparatus that may not form part of the text. This includes some types of notes, named entities, glossary information, and the like.

The view and the markup have in common that they supply editorial interventions, but the nature of those interventions may be different for different manuscripts. I think the basis behind such decisions can (and should) be supplied in an editorial introduction.

**Comment by mmwwah** [comment]
You write: *In many teaching situations, the interest will not be palaeographical and codicological issues, and it may be valuable to let provide a more traditionally-formatted text.*  Are you including spelling here too?  Because I think the demand for a regularized Ormulum will probably be very thin.  

What I think does have a market is an Ormulum with all the spelling intact but the words regularized ("i" converted to "in," abbreviations expanded, etc.).  

I may consult with AWB, CMT, and MF on this.  And, frankly, is this not a question for the advisory board as well?

**Comment by scottkleinman** [comment]
I think that Ormulum is a special case, but there is also room for variation even with less unusual texts, as well as room for individual editorial decisions. In the case of the Ormulum, I might represent those stacked letters as double letters in the critical view. Frankly, a lot of the special glyphs would typically go in the facsimile view, but I think the unique nature of Orm's spelling justifies their transfer to the diplomatic view. Likewise, a more diplomatic spelling might justified as belonging in the critical view.

Are you sure that "i" is an abbreviation for "in" and not a linguistic form? If the latter, you'd probably want to leave it.

**Comment by mmwwah** [comment]
Okay -- I wasn't sure if your "provide a more traditionally-formatted text" was general or Junius1-specific.

I'm pretty sure that "i" = "in," but I'll doublecheck as I go.  Thanks for the reminder (and this will now go on my list of things to make editorial notes for [which for tenure dossier I will consolidate into a proper critical intro/apparatus]).

**Comment by mmwwah** [comment]
Also,  you don't happen to know Mark Faulkner, do you?  Before I contact him out of the blue, it would be nice to make sure he's not a wanker and/or hard to work with.  I asked Sjoerd, and he said he didn't know MF but that I should be sure and check, as MF proclaims himself as one of the Oxford Boys (ptui).

**Comment by scottkleinman** [comment]
My point about "i" is that it may be a low-stress form of "in" (that is, Orm actually *said* "i"), rather than an abbreviation. Here's if the form is linguistic, the code would probably be left as "i". If it is an abbreviation, it would probably be
```xml
<choice>
    <abbr>i</abbr>
    <expan>in</expan>
</choice>
```
The [MED entry](http://quod.lib.umich.edu/cgi/m/mec/med-idx?type=id&id=MED22279) appears to call "i" an error, but I'm not sure I agree with that.

**Comment by mmwwah** [comment]
Yeah, I knew what you meant (although looking back, I see that I wasn't at all clear).

I'll look into the linguistic "i" (have put it on my list for later), but Orm uses "i" for "in" exclusively, or almost so.  i.e., I can't find a single use of "in," but it may be there.
