### ISSUE TITLE
encoding flaws

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#72]
Two related questions:
Is there an example in Laud 108 somewhere of encoding an inkblot?  I'm not clear from our guidelines on how to do that, and I'm going to need to.

Also, I know it is our policy not to encode any flaws to the page that existed before the scribe set quill to vellum, but there are some cases in Junius 1 where I think we should reconsider.  To wit:
![screen shot 2015-11-09 at 09 37 05](https://cloud.githubusercontent.com/assets/7809545/11036256/81bf0df6-86c5-11e5-9640-fc569dfee379.png)

**Comment by scottkleinman** [comment]
See [here](http://scottkleinman.net/wp-content/uploads/guidelines-4.0/Encoding_Policies/Representation_of_Characters_and_Glyphs/Stray_Marks,_Blots,_and_Stains) for handling these situations. In addition to using `<physDesc>`, you can describe the phenomenon in `<note type="cod">` at the point in the text.

I would need to see more of the image to be sure, but it looks like there is a connecting line of some sort written around the hole in the vellum. If that's the case, you may want to use a [metamark](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PH-meta). [This search](https://github.com/scottkleinman/aeme/search?utf8=%E2%9C%93&q=metamark) will show you some examples in Laud Misc. 108.

**Comment by mmwwah** [comment]
Yes, sometimes there are metamarks, and I was planning on encoding them.  

The reason I want to encode vellum flaws is the way that Orm deals with them.  That strikes me as being of interest to scholars using Junius 1 to study scribal practice.

I did read our Guidelines on how to encode inkblots etc; I was just wondering if we had an example in Laud 108.  Or is it too fastidious a manuscript for such slovenliness? ;-)

**Comment by scottkleinman** [comment]
In general ink blots do not obscure the text in Laud Misc. 108, so they have not been encoded. You could search the GitHub repo for the appropriate TEI tags and see if anything comes up.

The point you make about Orm's dealing with vellum flaws is valid, but it may have to wait for an implementation of the facsimile view, as I'm not sure that TEI has appropriate mechanisms for the diplomatic view. This might fall under the same rubric (no pun intended) as thirteenth-century pen flourishing. It would be nice if we could encode it, but there's no clear way to do so. Perhaps the best way to deal with this phenomenon is by using `<note type="cod">` and giving a prose explanation.

**Comment by mmwwah** [comment]
Okay, great.
