### ISSUE TITLE
VU (not Velvet Underground)

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#76]
The Guidelines say that I & J are kept distinct in both DipV and CritV.  Have y'all handled U & V likewise in Laud 108?  I don't have a strong opinion about whether to regularize them in the CritV.

**Comment by scottkleinman** [comment]
Good point. We have not regularised *u* and *v* in the critical markup. This is something that students actually struggle with quite a bit, though, so I might consider making a "student edition" stylesheet -- separate from the AEME infrastructure -- that normalises. But that would be for my own personal use (or for anyone else who wants it).

**Comment by mmwwah** [comment]
Okay, good.  I'm not regularizing.
