### ISSUE TITLE
double-csup

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#77]
Ponder, if you will, the superscript double C:
![screen shot 2015-11-12 at 13 49 24](https://cloud.githubusercontent.com/assets/7809545/11127863/68e00cbe-8944-11e5-872f-89a438392ea3.png)

The easiest way to encode these would be using `&#csup;` after each C, like this:
```Ic&#csup;c&#csup; hafe blah blah blah```

But esp.  in the first case in that screen shot, it doesn't really reflect what's on the page: It's not a case of a superscript C above each of the two Cs in the body of the word, but rather a superscript CC floating in that general space.

Opinions?  Use `&#csup;` for now and deal with later?

**Comment by scottkleinman** [comment]
My initial interpretation is `Icc<add place="supralinear">&csup;&csup;</add>`. That assumes that the superscripted "cc" was added after the initial writing, but I'm not at all sure that is a correct interpretation. Why are the superscripted c's there? Do they have a purpose?

**Comment by mmwwah** [comment]
No freaking clue why they're there (me or any of the other scholars, to my knowledge).  They are the same ink, it is generally agreed.

**Comment by scottkleinman** [comment]
I can't add much. One of my students working in Laud Misc. 108 observes that the superscript "cc" has the letters more clearly distinct. If that helps...

**Comment by mmwwah** [comment]
I don't quite follow.  More clearly distinct than what?

**Comment by scottkleinman** [comment]
I think it's just that the "cc" appears less ligatured (more space between the letters).

**Comment by mmwwah** [comment]
Got it.

I think I'm going to just `&csup;` them for now.  We can think further about it later.
