### ISSUE TITLE
euphemism policy?

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#79]
Do we have a policy for euphemisms and `#bio` references?  At the moment I'm looking at *Min Drihhten*, but I can imagine all other kinds of euphemisms.  Bio-tag them or no?  (And should we add a line in the Guidelines accordingly?)

**Comment by scottkleinman** [comment]
Any encoding of this type would be on top of the minimal markup schema, so there's no policy in place. Initially, I'm not sure that we'll be able to implement search functionality in the AEME interface, but one can easily open the code and use control+F with the `@xmlid` (or script it if one has the technical competence).

But this does raise a question. If you *want* to include this information, is there a standard why of encoding it? I think the standard TEI method would be as follows. Assuming God is defined somewhere as `@xmld="God"`:

```xml
<name type="person" ref="#God">Godd</name, <seg corresp="#God">Min Drihhten</seg>
```
See [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SACS](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SACS). Is there any reason why AEME may need a different or procedure from (or more restrictive procedure than) standard TEI?

**Comment by mmwwah** [comment]
I guess I was being more naive about it.  I was envisioning something like this:
```<name type="person" ref="#bioGod001">Min Drihhten</name>```

**Comment by scottkleinman** [comment]
Ah yes, that's that little dance of making the markup semantic. "Min Drihhten" isn't a name, so you don't want to use `<name>`. So the question is whether the TEI *drihhtenness* have thought of a semantic alternative. I think in this case they have.

**Comment by mmwwah** [comment]
Right.  Got it.

I think I'll skip the euphemisms for now.
