### ISSUE TITLE
erasures

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#82]
Am I right in assuming that obvious erasures where there is no trace of text remaining will only be rendered in the FacsV?  I'm assuming that because a blank with scrape marks holds no semantic value, and because I don't see anything under the guidelines for `<del>` that would be of use... but correct me if I'm wrong.

**Comment by scottkleinman** [comment]
I think this would be handled by one of the first two bullet points in the TEI recommendations listed [here](http://scottkleinman.net/wp-content/uploads/guidelines-4.0/The_text_Section/Unclear_or_Illegible_Characters). A don't think `<gap>` would be rendered  in anything but the facsimile view.

**Comment by mmwwah** [comment]
Great -- thanks.  Done.
