### ISSUE TITLE
overwritten correction

### ISSUE THREAD

**Issue by mmwwah** [scottkleinman/aeme#85]
What's the element to signal that a scribe has written the desired character over the undesired character?  `<del>` and `<add>` don't really do it, and I couldn't find anything in our Guidelines or in the TEI Guidelines (although no doubt it is somewhere in the latter).  `<corr>` doesn't seem to apply to original scribes.

**Comment by scottkleinman** [comment]
```xml
<del rend="overwritten">wrong text</del><add place="inline">right text</add>
```

**Comment by mmwwah** [comment]
But doesn't that describe them as next to each other rather than one over the other?

**Comment by scottkleinman** [comment]
It could, I suppose. The deletion will not be displayed in the critical view, so I think of the addition as flowing left. In the diplomatic view, you have to display one element or the other, unless you really want to start playing with text overlays in your css. I would suggest that that might be more appropriate for the facsimile view. But I'll look into this further.

**Comment by mmwwah** [comment]
Okay, that works for me.  I'll use the above and worry about details later.  Thanks!

**Comment by scottkleinman** [comment]
OK, it appears that you can explicitly mark the addition as a substitution for the deletion in the following way:

```xml
<subst>
    <del rend="overwritten">wrong text</del>
    <add place="inline">right text</add>
</subst>
```

See [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PHSU](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PHSU).
