### ISSUE TITLE
Multiple abbreviations

### ISSUE THREAD

**Issue by zabt** [scottkleinman/aeme#86]
If there are multiple abbreviations within one word, should they be contained within one <choice> tag or  multiple?  For example:

               q<choice>
                  <abbr>&isup;</abbr>
                  <expan>ui</expan>
               </choice>da<choice>
                  <abbr>&combmacr;</abbr>
                  <expan>m</expan>
               </choice>

or 

              <choice>q
                  <abbr>&isup;</abbr>
                  <expan>ui</expan>
                  da
                  <abbr>&combmacr;</abbr>
                  <expan>m</expan>
              </choice>

Also more generally are <choice> tags for whole words or individual instances of abbreviations?  Thanks.

**Comment by scottkleinman** [comment]
Neither will break the stylesheet parsing, but it's best to use fewer `<choice>` elements. The main issue is that `<abbr>` and `<expan>` are (at least in the latest the latest TEI recommendation) best used for "whole word" abbreviations and expansions like "Ihc" = "Iesu". For the "quindam" example you give, they've replaced by [`<am>`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-am.html) (abbreviation marker) and [`<ex>`](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-ex.html) (editorial expansion). So a good way to treat this word would be

```xml
<choice>
    q
    <am>&isup;</am>
    <ex>ui</ex>
    da
    <am>&combmacr;</am>
    <ex>m</ex>
</choice>
```
(Not necessarily indented this way, but oXygen's indentation feature will find the most readable layout.)

**Comment by zabt** [comment]
Nice.  Thank you.  I had been wondering about that difference as well.
